/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.mydsl1.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.xtext.example.mydsl1.services.MyDslGrammarAccess;
import robotmodel.Expression;
import robotmodel.IfStatement;
import robotmodel.Name;
import robotmodel.Script;
import robotmodel.Statement;

@SuppressWarnings("all")
public class MyDslFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private MyDslGrammarAccess _myDslGrammarAccess;
  
  protected void _format(final Script script, @Extension final IFormattableDocument document) {
    document.<Name>format(script.getName());
    EList<Statement> _statements = script.getStatements();
    for (final Statement statement : _statements) {
      document.<Statement>format(statement);
    }
  }
  
  protected void _format(final IfStatement ifStatement, @Extension final IFormattableDocument document) {
    document.<Expression>format(ifStatement.getIfExpression());
    EList<Statement> _statements = ifStatement.getStatements();
    for (final Statement statement : _statements) {
      document.<Statement>format(statement);
    }
    EList<Statement> _statements2 = ifStatement.getStatements2();
    for (final Statement statement_1 : _statements2) {
      document.<Statement>format(statement_1);
    }
  }
  
  public void format(final Object ifStatement, final IFormattableDocument document) {
    if (ifStatement instanceof XtextResource) {
      _format((XtextResource)ifStatement, document);
      return;
    } else if (ifStatement instanceof IfStatement) {
      _format((IfStatement)ifStatement, document);
      return;
    } else if (ifStatement instanceof Script) {
      _format((Script)ifStatement, document);
      return;
    } else if (ifStatement instanceof EObject) {
      _format((EObject)ifStatement, document);
      return;
    } else if (ifStatement == null) {
      _format((Void)null, document);
      return;
    } else if (ifStatement != null) {
      _format(ifStatement, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(ifStatement, document).toString());
    }
  }
}
