/**
 * generated by Xtext 2.12.0
 */
package nl.tue.robot;

import nl.tue.robot.RobotStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class RobotStandaloneSetup extends RobotStandaloneSetupGenerated {
  public static void doSetup() {
    new RobotStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
