/**
 * generated by Xtext 2.12.0
 */
package nl.tue.robot;

import nl.tue.robot.AbstractRobotRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class RobotRuntimeModule extends AbstractRobotRuntimeModule {
}
