/*
 * generated by Xtext 2.12.0
 */
package nl.tue.robot.serializer;

import com.google.inject.Inject;
import java.util.List;
import nl.tue.robot.services.RobotGrammarAccess;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class RobotSyntacticSequencer extends AbstractSyntacticSequencer {

	protected RobotGrammarAccess grammarAccess;
	protected AbstractElementAlias match_IfStatement___ElseKeyword_5_0_DoKeyword_5_1__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (RobotGrammarAccess) access;
		match_IfStatement___ElseKeyword_5_0_DoKeyword_5_1__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getIfStatementAccess().getElseKeyword_5_0()), new TokenAlias(false, false, grammarAccess.getIfStatementAccess().getDoKeyword_5_1()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_IfStatement___ElseKeyword_5_0_DoKeyword_5_1__q.equals(syntax))
				emit_IfStatement___ElseKeyword_5_0_DoKeyword_5_1__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ('else' 'do')?
	 *
	 * This ambiguous syntax occurs at:
	 *     command+=Statement (ambiguity) 'end' (rule end)
	 *     condition=Expression 'do' (ambiguity) 'end' (rule end)
	 */
	protected void emit_IfStatement___ElseKeyword_5_0_DoKeyword_5_1__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
