/*
 * generated by Xtext 2.12.0
 */
package nl.tue.robot.ide

import com.google.inject.Guice
import nl.tue.robot.RobotRuntimeModule
import nl.tue.robot.RobotStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class RobotIdeSetup extends RobotStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new RobotRuntimeModule, new RobotIdeModule))
	}
	
}
