/*
 * generated by Xtext 2.12.0
 */
package nl.tue.robot.ui;

import com.google.inject.Injector;
import nl.tue.robot.ui.internal.RobotActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RobotExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return RobotActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return RobotActivator.getInstance().getInjector(RobotActivator.NL_TUE_ROBOT_ROBOT);
	}
	
}
