/**
 * generated by Xtext 2.12.0
 */
package nl.tue.robot.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
@SuppressWarnings("all")
public class RobotOutlineTreeProvider extends DefaultOutlineTreeProvider {
}
