/*
 * generated by Xtext 2.12.0
 */
package nl.tue.robot.parser.antlr;

import com.google.inject.Inject;
import nl.tue.robot.parser.antlr.internal.InternalRobotParser;
import nl.tue.robot.services.RobotGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class RobotParser extends AbstractAntlrParser {

	@Inject
	private RobotGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRobotParser createParser(XtextTokenStream stream) {
		return new InternalRobotParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Script";
	}

	public RobotGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RobotGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
