/*
 * generated by Xtext 2.12.0
 */
package nl.tue.robot.ui.tests;

import com.google.inject.Injector;
import nl.tue.robot.ui.internal.RobotActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class RobotUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RobotActivator.getInstance().getInjector("nl.tue.robot.Robot");
	}

}
