/**
 * generated by Xtext 2.12.0
 */
package nl.tue.robot.ui.contentassist;

import nl.tue.robot.ui.contentassist.AbstractRobotProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class RobotProposalProvider extends AbstractRobotProposalProvider {
}
