/**
 * generated by Xtext 2.12.0
 */
package nl.tue.robot.scoping;

import nl.tue.robot.scoping.AbstractRobotScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class RobotScopeProvider extends AbstractRobotScopeProvider {
}
