/**
 * generated by Xtext 2.12.0
 */
package nl.tue.robot.ide;

import nl.tue.robot.ide.AbstractRobotIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class RobotIdeModule extends AbstractRobotIdeModule {
}
