/**
 * generated by Xtext 2.12.0
 */
package nl.tue.robot.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import nl.tue.robot.RobotRuntimeModule;
import nl.tue.robot.RobotStandaloneSetup;
import nl.tue.robot.ide.RobotIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class RobotIdeSetup extends RobotStandaloneSetup {
  @Override
  public Injector createInjector() {
    RobotRuntimeModule _robotRuntimeModule = new RobotRuntimeModule();
    RobotIdeModule _robotIdeModule = new RobotIdeModule();
    return Guice.createInjector(Modules2.mixin(_robotRuntimeModule, _robotIdeModule));
  }
}
