/**
 * generated by Xtext 2.12.0
 */
package nl.tue.robot.validation;

import nl.tue.robot.validation.AbstractRobotValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class RobotValidator extends AbstractRobotValidator {
}
