/*
 * generated by Xtext 2.12.0
 */
package nl.tue.robot.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRobotScopeProvider extends DelegatingScopeProvider {
}
