/**
 * generated by Xtext 2.12.0
 */
package nl.tue.robot.ui;

import nl.tue.robot.ui.AbstractRobotUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class RobotUiModule extends AbstractRobotUiModule {
  public RobotUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
